import type { Metadata } from "next";
import { getArticlesWithSummary, getPopularKeywords } from "@/lib/articles";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import AdUnit from "@/components/AdUnit";
import AiArticleList from "./AiArticleList";

export const metadata: Metadata = {
  title: "AI Curated News | Headlines Fazr",
  description:
    "Latest global news summaries generated by AI. Stay informed with quick, accurate summaries of trending articles.",
  alternates: {
    canonical: "https://headlines.fazr.co.kr/ai",
  },
};

export default async function AiPage() {
  const [articles, keywords] = await Promise.all([
    getArticlesWithSummary(30),
    getPopularKeywords(15),
  ]);

  return (
    <div className="min-h-screen bg-background">
      <Header />
      <main className="max-w-[1200px] mx-auto px-4 py-6">
        <div className="mb-6">
          <h1 className="text-2xl font-bold">AI Curated News</h1>
          <p className="text-sm text-muted-foreground mt-1">
            Latest global news summaries generated by AI · {articles.length} articles
          </p>
        </div>

        <AdUnit slot="top-ai" className="mb-6" />

        {keywords.length > 0 && (
          <div className="mb-6">
            <h2 className="text-sm font-bold mb-2">Popular Topics</h2>
            <div className="flex flex-wrap gap-2">
              {keywords.map((kw) => (
                <a
                  key={kw}
                  href={`/topic/${encodeURIComponent(kw)}`}
                  className="px-3 py-1 rounded-full text-xs bg-muted hover:bg-primary/10 hover:text-primary transition-colors"
                >
                  #{kw}
                </a>
              ))}
            </div>
          </div>
        )}

        <AiArticleList articles={articles} />

        <AdUnit slot="bottom-ai" className="mt-6" />
      </main>
      <Footer />
    </div>
  );
}
